### ISSUE TITLE
Camera.toString() fails because of unrecognized field

### ISSUE THREAD

**Issue by claudiocherubino** [nestlabs/android-sdk#10]
04-25 17:35:55.325  3182  3182 E AndroidRuntime: com.firebase.client.FirebaseException: Failed to bounce to type
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.firebase.client.DataSnapshot.getValue(DataSnapshot.java:186)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.nestlabs.sdk.GlobalValueListener.onDataChange(GlobalValueListener.java:61)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.firebase.client.core.ValueListenerContainer$1.run(ValueListenerContainer.java:47)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6010)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "REDACTED" (class com.nestlabs.sdk.Camera), not marked as ignorable (16 known properties: , "software_version", "device_id", "web_url", "last_connection", "structure_id", "is_online", "name", "is_streaming", "is_audio_input_enabled", "name_long", "last_is_online_change" [truncated]])
04-25 17:35:55.325  3182  3182 E AndroidRuntime:  at [Source: java.io.StringReader@291e57a; line: 1, column: 796] (through reference chain: com.nestlabs.sdk.Camera["REDACTED"])
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	at com.firebase.client.DataSnapshot.getValue(DataSnapshot.java:182)
04-25 17:35:55.325  3182  3182 E AndroidRuntime: 	... 9 more

**Comment by ryanseys** [comment]
I have have to apply `@JsonIgnoreProperties(ignoreUnknown = true)` to these classes as a fix for newly created unknown properties.

@beriberikix @aurman In the future, when new fields are added to the API objects, this library should be updated to accomodate these values.

**Comment by claudiocherubino** [comment]
Thermostat has a similar issue:

04-25 17:42:51.405   957   957 E AndroidRuntime: Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "locked_temp_max_f" (class com.nestlabs.sdk.Thermostat), not marked as ignorable (32 known properties: , "software_version", "hvac_state", "target_temperature_low_f", "is_online", "name", "hvac_mode", "can_cool", "locale", "away_temperature_low_c", "away_temperature_low_f", "target_temperature_high_c" [truncated]])

**Comment by beriberikix** [comment]
ack. But the `ignoreUnknown` fix will at least prevent future runtime errors until libraries are updated?

**Comment by ryanseys** [comment]
Yes you're correct.
