### ISSUE TITLE
0 Supported Devices on Google play when using this SDK

### ISSUE THREAD

**Issue by abhishekBansal** [nestlabs/android-sdk#5]
Hi,
It seems like following library dependancy in this SDK is creating trouble when we are uploading our app to Google Play Store

`compile 'org.apache.directory.studio:org.apache.commons.io:2.4' `

Google play shows 0 supported devices when nestlabs SDK is configured as a dependancy in my app.

Other people are also facing same issue with apache commons
See here 
http://stackoverflow.com/questions/14020237/android-app-is-supported-by-0-devices
and here
http://stackoverflow.com/questions/33308560/supported-android-devices-0-devices

**Comment by abhishekBansal** [comment]
Changing 
`compile 'org.apache.directory.studio:org.apache.commons.io:2.4'`
to 
`compile 'commons-io:commons-io:2.4'`
solves problem.

**Comment by davin12x** [comment]
Where to change? Do you mean by in sdk ?? cuz in project if i changed its the same error ..??

**Comment by harenj** [comment]
Issue #18 is the same thing, I resolved it there. This problem shouldn't exist anymore.
