### ISSUE TITLE
Is it possible to use username/password authentication ?

### ISSUE THREAD

**Issue by Vandalko** [nestlabs/android-sdk#7]
Firebase has `authWithPassword ` authentication method, but `NestApi` facade doesn't expose this method.

I wonder if it's possible to use Firebase directly and use username / password authentication ? Or it is something deprecated and prohibited ?

**Comment by Vandalko** [comment]
If only OAuth is supported, then how long does token lives (if user never revokes it manually) ?

**Comment by ryanseys** [comment]
Nest doesn't allow third-party sign-in using a password (for obvious security reasons). The token lasts 10 years :)
