### ISSUE TITLE
Is it possible to query rate limits ?

### ISSUE THREAD

**Issue by Vandalko** [nestlabs/android-sdk#8]
I've just noticed that it's very easy to hit request rate limit.
Is it possible to get info about current rate limit ?
Also, when we receive rate limit error, is there any event / listener to be notified when we can send requests again ?

**Comment by Vandalko** [comment]
btw, is it correct place for such questions or they should be asked on SO with `nest-api` tag ?

**Comment by unexpected62** [comment]
Regarding data rate limits, I found this: https://developer.nest.com/documentation/cloud/data-rate-limits/
I personally think you should post on SO with nest-api tag. Nest seems to agree, as in their own documentation (like the aforementioned link) at the bottom it says, "More questions about the Nest API? Visit StackOverflow" and links to the `nest-api` tag.

**Comment by Vandalko** [comment]
@unexpected62 thx for suggestion
http://stackoverflow.com/questions/36560591/is-it-possible-to-query-nest-api-rate-limits
